#!/usr/bin/env node

/**
 * ビルド時にget-version.tsをVERSION定数に置き換える
 *
 * WHY: 開発時は動的にバージョンを取得し、ビルド時には静的に埋め込むため
 * WHY: 配布されたバイナリでGitコマンドが不要になるようにするため
 */

import { execSync } from 'node:child_process';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';

function getVersionString(): string {
  try {
    // package.jsonのバージョンを取得
    const packageJsonPath = path.join(process.cwd(), 'package.json');
    const packageJson = JSON.parse(
      execSync(`cat ${packageJsonPath}`, { encoding: 'utf-8' }),
    );
    const pkgVersion = packageJson.version;

    // 現在のコミットに対応するGitタグを取得
    try {
      const gitTag = execSync('git describe --tags --exact-match', {
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'pipe'],
      }).trim();

      // タグがvX.Y.Z形式の場合はv接頭辞を削除
      const tagVersion = gitTag.startsWith('v') ? gitTag.slice(1) : gitTag;

      // タグがpackage.jsonのバージョンと一致する場合
      if (tagVersion === pkgVersion) {
        return pkgVersion;
      }
    } catch {
      // タグがない場合は何もしない
    }

    // タグがないか、一致しない場合はコミットハッシュを返す
    const commitHash = execSync('git rev-parse --short HEAD', {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();

    return commitHash;
  } catch {
    // Gitが利用できない場合やエラーの場合はpackage.jsonのバージョンを返す
    return '0.1.0';
  }
}

async function main() {
  const version = getVersionString();

  // get-version.tsを読み込んで、VERSION定数に置き換える
  const versionFileContent = `/**
 * ビルド時に自動生成されたバージョン情報
 * @generated by scripts/generate-version.ts
 */
export const VERSION = '${version}';
export function getVersion(): string {
  return VERSION;
}
`;

  const outputPath = path.join(
    process.cwd(),
    'src',
    'cli',
    'utils',
    'get-version.ts',
  );

  // 元のファイルをバックアップ（ビルド後に復元するため）
  const backupPath = path.join(
    process.cwd(),
    'src',
    'cli',
    'utils',
    'get-version.ts.original',
  );
  await fs.copyFile(outputPath, backupPath);

  try {
    await fs.writeFile(outputPath, versionFileContent, 'utf-8');
    console.log(
      `✅ Version inlined in get-version.ts (version: ${version})`,
    );
  } catch (error) {
    // エラーが発生したらバックアップから復元
    await fs.copyFile(backupPath, outputPath);
    await fs.unlink(backupPath);
    throw error;
  }
}

main().catch((error) => {
  console.error('❌ Failed to generate version:', error);
  process.exit(1);
});
