/**
 * Worker Operations - タスク実装を担当する関数群
 *
 * Workerクラスを関数型パターンで再実装。
 * タスクごとにworktreeを作成し、エージェントを実行して実装を行う。
 */

import path from 'node:path';
import { spawn } from 'node:child_process';
import type { Result } from 'option-t/plain_result';
import { createOk, createErr, isErr } from 'option-t/plain_result';
import type { Task } from '../../types/task.ts';
import type { TaskId, WorktreePath, RepoPath, BranchName } from '../../types/branded.ts';
import { runId, repoPath } from '../../types/branded.ts';
import type { GitEffects } from '../../adapters/vcs/git-effects.ts';
import type { RunnerEffects } from '../runner/runner-effects.ts';
import type { TaskStore } from '../task-store/interface.ts';
import type { OrchestratorError } from '../../types/errors.ts';
import { createInitialRun, RunStatus } from '../../types/run.ts';
import type { Config } from '../../types/config.ts';
import type { ConflictContent, ConflictResolutionInfo } from '../../types/integration.ts';
import type { BaseBranchResolution } from './base-branch-resolver.ts';

/**
 * Worktree作成結果
 *
 * WHY: コンフリクトがある場合も worktree は作成されるため、エラーではなく状態として返す
 */
export type WorktreeSetupResult =
  | { type: 'success'; worktreePath: WorktreePath }
  | { type: 'with_conflicts'; worktreePath: WorktreePath; conflictInfo: ConflictResolutionInfo };

/**
 * Worker依存関係
 */
export interface WorkerDeps {
  readonly gitEffects: GitEffects;
  readonly runnerEffects: RunnerEffects;
  readonly taskStore: TaskStore;
  readonly appRepoPath: RepoPath;
  readonly agentCoordPath: string;
  readonly agentType: 'claude' | 'codex';
  readonly model: string;
  readonly config: Config;
}

/**
 * Worker実行結果
 */
export interface WorkerResult {
  /** 実行ID */
  readonly runId: string;
  /** 成功したか */
  readonly success: boolean;
  /** エラーメッセージ（失敗時） */
  readonly error?: string;
}

/**
 * エージェント種別
 */
export type AgentType = 'claude' | 'codex';

/**
 * 自動生成ファイルの判定
 *
 * WHY: node_modules/やlockファイルはLLMによる解決が不適切なため、特別扱いが必要
 */
const isAutoGeneratedFile = (filePath: string): boolean => {
  const autoGeneratedPatterns = [
    // パッケージマネージャーのファイル
    /^node_modules\//,
    /^\.pnpm\//,
    /pnpm-lock\.yaml$/,
    /package-lock\.json$/,
    /yarn\.lock$/,
    // ビルド出力
    /^dist\//,
    /^build\//,
    /^\.next\//,
    // キャッシュ
    /^\.cache\//,
    /^\.turbo\//,
  ];

  return autoGeneratedPatterns.some((pattern) => pattern.test(filePath));
};

/**
 * バイナリファイルの判定
 *
 * WHY: バイナリファイルは自動解決不可能なため、事前にチェックする
 */
const isBinaryFile = (filePath: string): boolean => {
  const binaryExtensions = [
    // 画像
    '.png',
    '.jpg',
    '.jpeg',
    '.gif',
    '.bmp',
    '.ico',
    '.webp',
    '.svg',
    // ドキュメント
    '.pdf',
    '.doc',
    '.docx',
    '.xls',
    '.xlsx',
    '.ppt',
    '.pptx',
    // アーカイブ
    '.zip',
    '.tar',
    '.gz',
    '.rar',
    '.7z',
    // バイナリ実行ファイル
    '.exe',
    '.dll',
    '.so',
    '.dylib',
    // その他
    '.bin',
    '.dat',
    '.db',
    '.sqlite',
  ];
  const ext = path.extname(filePath).toLowerCase();
  return binaryExtensions.includes(ext);
};

/**
 * 自動解決をスキップすべきか判定
 *
 * WHY: バイナリファイル・自動生成ファイル・拡張子なし実行ファイルは
 *      LLMによる解決が不適切または不可能なため、自動解決対象から除外
 */
/**
 * シェルコマンドを実行
 *
 * WHY: pnpm install などのコマンドを実行するためのヘルパー関数
 */
const runCommand = (
  cwd: string,
  command: string,
  args: string[],
): Promise<Result<string, Error>> => {
  return new Promise((resolve) => {
    const proc = spawn(command, args, { cwd, shell: true });
    let stdout = '';
    let stderr = '';

    proc.stdout?.on('data', (data: Buffer) => {
      stdout += data.toString();
    });

    proc.stderr?.on('data', (data: Buffer) => {
      stderr += data.toString();
    });

    proc.on('close', (code) => {
      if (code === 0) {
        resolve(createOk(stdout));
      } else {
        resolve(createErr(new Error(`Command failed with code ${code}: ${stderr}`)));
      }
    });

    proc.on('error', (err) => {
      resolve(createErr(err));
    });
  });
};

export const shouldSkipAutoResolution = (
  filePath: string,
): { skip: boolean; reason: string; isLockfile: boolean; isNodeModules: boolean } => {
  // Lockファイルの判定
  const isLockfile =
    filePath.endsWith('pnpm-lock.yaml') ||
    filePath.endsWith('package-lock.json') ||
    filePath.endsWith('yarn.lock');

  // node_modules配下の判定
  const isNodeModules = filePath.startsWith('node_modules/') || filePath.startsWith('.pnpm/');

  // 自動生成ファイル
  if (isAutoGeneratedFile(filePath)) {
    return { skip: true, reason: 'auto-generated file', isLockfile, isNodeModules };
  }

  // バイナリファイル
  if (isBinaryFile(filePath)) {
    return { skip: true, reason: 'binary file', isLockfile: false, isNodeModules: false };
  }

  // 拡張子なしファイル（node_modules/.bin/* など）
  const ext = path.extname(filePath);
  if (ext === '' && filePath.includes('/.bin/')) {
    return { skip: true, reason: 'executable without extension', isLockfile: false, isNodeModules };
  }

  return { skip: false, reason: '', isLockfile: false, isNodeModules: false };
};

/**
 * コミットメッセージを生成（純粋関数）
 */
export const generateCommitMessage = (task: Task): string => {
  return `feat: ${task.acceptance}

Task ID: ${task.id}
Branch: ${task.branch}

🤖 Generated with Agent Orchestrator
`;
};

/**
 * Worker操作を生成するファクトリ関数
 */
export const createWorkerOperations = (deps: WorkerDeps) => {
  const toRelativePath = (targetPath: string): string => {
    const absolutePath = path.resolve(targetPath);
    const relativePath = path.relative(process.cwd(), absolutePath);
    return relativePath === '' ? '.' : relativePath;
  };

  const getRunDisplayPath = (runIdValue: string, ext: 'log' | 'json'): string => {
    return toRelativePath(path.join(deps.agentCoordPath, 'runs', `${runIdValue}.${ext}`));
  };

  /**
   * タスク用のworktreeを作成
   *
   * ブランチが存在しない場合は新規作成します。
   *
   * WHY: ブランチ名にタスクIDを含めることで、並列実行時の衝突を防ぐ
   * 例: feature/auth → feature/auth-task-2b8c0253-1
   *
   * WHY: Phase 2 - 統合ブランチから再実行する場合、新しいworktreeを作成
   *      元のworktreeは元のブランチを指しているため、rebaseによるブランチ切り替えはリスクが高い
   *      新しいworktreeを作成することで、元のブランチの状態を保持しつつ、統合ブランチから実行可能
   *
   * @param task タスク
   * @param baseBranch 起点となるブランチ（新規ブランチ作成時のみ使用）
   * @returns worktreeのパス（Result型）
   */
  const setupWorktree = async (
    task: Task,
    baseBranch?: BranchName,
  ): Promise<Result<WorktreePath, OrchestratorError>> => {
    // タスクのブランチ名を取得（Plannerが既にタスクIDを含めている）
    const taskBranchName = task.branch;

    // ブランチが存在するか確認
    const branchesResult = await deps.gitEffects.listBranches(deps.appRepoPath);
    if (isErr(branchesResult)) {
      return createErr(branchesResult.err);
    }

    const branches = branchesResult.val;
    const branchExists = branches.some((b) => b.name === taskBranchName);

    // WHY: Phase 2 - 統合ブランチから再実行する場合、新しいworktree名を使用
    //      元のworktreeと区別するため、サフィックスを追加
    const worktreeName = task.integrationRetried
      ? `${task.id}-integration`
      : String(task.id);

    // Worktreeを作成（createBranchフラグでブランチも同時作成）
    // WHY: baseBranch指定時は、そのブランチから分岐（依存関係を反映）
    const worktreeResult = await deps.gitEffects.createWorktree(
      deps.appRepoPath,
      worktreeName,
      taskBranchName,
      !branchExists,
      baseBranch,
    );

    return worktreeResult;
  };

  /**
   * コンフリクト解消プロンプトを構築（インライン解決用）
   *
   * WHY: Worker実行中にその場でコンフリクトを解決するためのプロンプト
   *
   * @param conflictInfo コンフリクト情報
   * @returns プロンプト文字列
   */
  const buildConflictResolutionPromptInline = (conflictInfo: ConflictResolutionInfo): string => {
    const lines: string[] = [
      '# ⚠️  Merge Conflict Resolution Required',
      '',
      'Before executing your main task, you must resolve merge conflicts that occurred',
      'while merging dependency branches.',
      '',
      `Source branch: ${conflictInfo.sourceBranch}`,
      `Target branch: ${conflictInfo.targetBranch}`,
      '',
      'The following merge conflicts must be resolved:',
      '',
    ];

    for (const detail of conflictInfo.conflictContents) {
      lines.push(`## File: ${detail.filePath}`);
      lines.push(`Conflicting branch: ${detail.theirBranch}`);
      lines.push('');
      lines.push('### Our version (current branch):');
      lines.push('```');
      lines.push(detail.oursContent);
      lines.push('```');
      lines.push('');
      lines.push('### Their version (incoming branch):');
      lines.push('```');
      lines.push(detail.theirsContent);
      lines.push('```');
      lines.push('');
      if (detail.baseContent) {
        lines.push('### Base version (common ancestor):');
        lines.push('```');
        lines.push(detail.baseContent);
        lines.push('```');
        lines.push('');
      }
    }

    lines.push('## Instructions');
    lines.push('');
    lines.push('1. Analyze both versions and understand the intent of each change');
    lines.push('2. Resolve conflicts by choosing appropriate content or merging both changes');
    lines.push('3. Edit the conflicted files to resolve all conflicts');
    lines.push(
      '4. Ensure the resolved code compiles and maintains functionality from both versions',
    );
    lines.push('5. DO NOT commit - the orchestrator will commit after resolution');
    lines.push('');
    lines.push('After resolving all conflicts, your main task will be executed.');

    return lines.join('\n');
  };

  /**
   * 複数依存タスク用のworktreeを作成し、依存ブランチをマージ
   *
   * WHY: メインリポジトリのHEADを変更せず、worktree内でマージを実行することで
   *      並列実行時のGit操作競合を防ぐ
   *
   * WHY: コンフリクト発生時も worktree は作成されているため、エラーではなく
   *      コンフリクト情報付きの結果として返す
   *
   * @param task タスク
   * @param dependencyBranches 依存ブランチのリスト
   * @returns worktree作成結果（コンフリクト情報を含む可能性あり）
   */
  const setupWorktreeWithMerge = async (
    task: Task,
    dependencyBranches: readonly BranchName[],
  ): Promise<Result<WorktreeSetupResult, OrchestratorError>> => {
    if (dependencyBranches.length === 0) {
      return createErr({
        type: 'ValidationError',
        details: 'dependencyBranches must not be empty',
        message: 'setupWorktreeWithMerge called with empty dependencyBranches',
      });
    }

    // 1. 最初の依存ブランチからworktree作成
    const firstBranch = dependencyBranches[0]!;
    const worktreeResult = await setupWorktree(task, firstBranch);
    if (isErr(worktreeResult)) {
      return createErr(worktreeResult.err);
    }

    const worktreePath = worktreeResult.val;

    // 依存が1つだけの場合はマージ不要
    if (dependencyBranches.length === 1) {
      return createOk({ type: 'success', worktreePath });
    }

    const mergedBranches: BranchName[] = [firstBranch];

    // 2. worktree内で残りの依存ブランチを順次マージ
    for (let i = 1; i < dependencyBranches.length; i++) {
      const branchToMerge = dependencyBranches[i]!;
      const mergeResult = await deps.gitEffects.merge(repoPath(worktreePath), branchToMerge);

      if (isErr(mergeResult)) {
        // マージエラー: マージを中断し、worktreeをクリーンアップしてエラーを返す
        await deps.gitEffects.abortMerge(repoPath(worktreePath));
        await cleanupWorktree(task.id);
        return createErr(mergeResult.err);
      }

      const merge = mergeResult.val;

      if (merge.hasConflicts) {
        // コンフリクト発生: カテゴリ別に分類して処理
        // WHY: Worker自身がその場で解決することで、タスク失敗→依存ブロックの連鎖を防ぐ

        const lockfileConflicts: string[] = [];
        const nodeModulesConflicts: string[] = [];
        const binaryConflicts: string[] = [];
        const textConflicts: string[] = [];

        for (const conflict of merge.conflicts) {
          const resolution = shouldSkipAutoResolution(conflict.filePath);
          if (resolution.isLockfile) {
            lockfileConflicts.push(conflict.filePath);
          } else if (resolution.isNodeModules) {
            nodeModulesConflicts.push(conflict.filePath);
          } else if (resolution.skip && resolution.reason === 'binary file') {
            binaryConflicts.push(conflict.filePath);
          } else if (!resolution.skip) {
            textConflicts.push(conflict.filePath);
          } else {
            // その他の自動解決スキップ対象（拡張子なし実行ファイルなど）
            nodeModulesConflicts.push(conflict.filePath);
          }
        }

        // バイナリファイルのコンフリクトが含まれる場合はエラー
        if (binaryConflicts.length > 0) {
          console.log(
            `  ⚠️  Binary file conflicts detected: ${binaryConflicts.join(', ')} (cannot auto-resolve)`,
          );
          await deps.gitEffects.abortMerge(repoPath(worktreePath));
          await cleanupWorktree(task.id);
          return createErr({
            type: 'ValidationError',
            message: `Cannot auto-resolve binary file conflicts: ${binaryConflicts.join(', ')}`,
            details: 'Binary files require manual conflict resolution',
          });
        }

        // Phase 3: lockfile/node_modulesコンフリクトを自動解決
        const autoResolvedCount = lockfileConflicts.length + nodeModulesConflicts.length;
        if (autoResolvedCount > 0) {
          console.log(`  🔧 Auto-resolving ${autoResolvedCount} generated file conflicts`);

          for (const filePath of [...lockfileConflicts, ...nodeModulesConflicts]) {
            // --ours を採用（どちらでも良い、後で再生成される）
            const checkoutResult = await deps.gitEffects.raw?.(
              repoPath(worktreePath),
              ['checkout', '--ours', filePath],
            );
            if (checkoutResult && !checkoutResult.ok) {
              console.log(`  ⚠️  Failed to checkout --ours for ${filePath}: ${checkoutResult.err.message}`);
            }

            const markResult = await deps.gitEffects.markConflictResolved(
              repoPath(worktreePath),
              filePath,
            );
            if (!markResult.ok) {
              console.log(`  ⚠️  Failed to mark ${filePath} as resolved: ${markResult.err.message}`);
            }
          }
        }

        // テキストファイルのコンフリクトのみをWorkerに任せる
        if (textConflicts.length > 0) {
          const conflictDetails: ConflictContent[] = [];

          for (const filePath of textConflicts) {
            const contentResult = await deps.gitEffects.getConflictContent(
              repoPath(worktreePath),
              filePath,
            );
            if (contentResult.ok) {
              conflictDetails.push(contentResult.val);
            }
          }

          // テキストコンフリクトがある場合はWorkerに解決を依頼
          const conflictInfo: ConflictResolutionInfo = {
            taskId: task.id,
            sourceBranch: branchToMerge,
            targetBranch: task.branch,
            conflicts: merge.conflicts.filter((c) => textConflicts.includes(c.filePath)),
            conflictContents: conflictDetails,
            // Phase 4: 自動解決したファイルがある場合、再インストールが必要
            needsReinstall: autoResolvedCount > 0,
          };

          return createOk({
            type: 'with_conflicts',
            worktreePath,
            conflictInfo,
          });
        }

        // 自動生成ファイルのみのコンフリクトだった場合
        if (autoResolvedCount > 0 && textConflicts.length === 0) {
          console.log(`  ✅ All conflicts were auto-resolved (generated files only)`);

          // コミットして続行
          const commitResult = await deps.gitEffects.commit(
            repoPath(worktreePath),
            'Resolve generated file conflicts (auto-resolved)',
            { noGpgSign: !deps.config.commit.autoSignature },
          );

          if (!commitResult.ok) {
            // コミット失敗時はマージを中断してエラーを返す
            // WHY: マージ状態が残ったまま次のマージに進むとGitエラーになる
            console.log(`  ❌ Failed to commit auto-resolved conflicts: ${commitResult.err.message}`);
            await deps.gitEffects.abortMerge(repoPath(worktreePath));
            await cleanupWorktree(task.id);
            return createErr(commitResult.err);
          }

          console.log(`  ✅ Auto-resolved conflicts committed`);
          // マージ成功として扱う（次のブランチのマージに進む）
          mergedBranches.push(branchToMerge);
          continue;
        }
      }

      mergedBranches.push(branchToMerge);
    }

    // 全てのマージが成功
    return createOk({ type: 'success', worktreePath });
  };

  /**
   * タスクを実行（エージェント実行のみ）
   *
   * エージェントを起動してタスクを実行します。
   * 実行ログとメタデータをrunsディレクトリに保存します。
   * Git操作（commit、push）は別の関数で行います。
   *
   * @param task タスク
   * @param worktreePath worktreeのパス
   * @returns 実行結果（runIdと成功/失敗）
   */
  const executeTask = async (
    task: Task,
    worktreePath: WorktreePath,
  ): Promise<Result<WorkerResult, OrchestratorError>> => {
    // 1. runsディレクトリを確保
    const ensureResult = await deps.runnerEffects.ensureRunsDir();
    if (isErr(ensureResult)) {
      return createErr(ensureResult.err);
    }

    // 2. RunID生成（タスクIDベース）
    const timestamp = Date.now();
    const theRunId = runId(`run-${task.id}-${timestamp}`);
    const logPath = path.join(deps.agentCoordPath, 'runs', `${theRunId}.log`);

    // 3. 実行メタデータを初期化
    const run = createInitialRun({
      id: theRunId,
      taskId: task.id,
      agentType: deps.agentType,
      logPath,
      plannerRunId: task.plannerRunId ?? null,
      plannerLogPath: task.plannerLogPath ?? null,
      plannerMetadataPath: task.plannerMetadataPath ?? null,
    });

    // メタデータ保存
    const saveMetaResult = await deps.runnerEffects.saveRunMetadata(run);
    if (isErr(saveMetaResult)) {
      return createErr(saveMetaResult.err);
    }

    // ログファイルのヘッダーを初期化
    const initLogResult = await deps.runnerEffects.initializeLogFile(run);
    if (isErr(initLogResult)) {
      return createErr(initLogResult.err);
    }

    console.log(`  📝 Execution log: ${getRunDisplayPath(theRunId, 'log')}`);
    console.log(`  📊 Metadata: ${getRunDisplayPath(theRunId, 'json')}`);

    // 4. ログにタスク開始を記録
    await deps.runnerEffects.appendLog(
      theRunId,
      `[${new Date().toISOString()}] Starting task: ${task.acceptance}\n`,
    );
    await deps.runnerEffects.appendLog(theRunId, `Agent Type: ${deps.agentType}\n`);
    await deps.runnerEffects.appendLog(theRunId, `Worktree: ${worktreePath}\n\n`);

    // 5. エージェントを実行
    // WHY: 役割ごとに最適なモデルを使用（Config から取得）
    // WHY: task.context には詳細な実装指示が含まれるため、必ずプロンプトに含める
    let agentPrompt = `Execute task: ${task.acceptance}

${task.context ? `## IMPLEMENTATION DETAILS\n${task.context}\n` : ''}
${task.scopePaths.length > 0 ? `## FILES TO CREATE/MODIFY\n${task.scopePaths.join('\n')}\n` : ''}

⚠️  CRITICAL: You must IMPLEMENT the task, not just verify it.
- CREATE or MODIFY the files listed above
- If files already exist, verify they meet requirements OR update them
- Ensure your changes are saved and ready to be committed
- The "VERIFY" section describes how to validate completion, not the entire task

⚠️  IMPORTANT: You are working in an isolated worktree directory.
- Your working directory is: ${worktreePath}
- DO NOT use 'cd ..' or navigate outside this directory
- All work must be done within this directory
- The worktree is properly configured with the correct branch

⚠️  IMPORTANT: DO NOT create report files in the repository
- DO NOT create VERIFICATION_REPORT.md or any other report files
- Output verification results directly to logs (stdout/stderr)
- Use console.log, console.error for verification output
- Reports are automatically saved to the runs/ directory by the orchestrator`;

    // フィードバックがある場合は追加（継続実行のため）
    // WHY: 前回の判定で指摘された問題を明示することで、エージェントが適切に対処できる
    if (task.judgementFeedback) {
      agentPrompt += `\n\n⚠️  Previous attempt (iteration ${task.judgementFeedback.iteration}/${task.judgementFeedback.maxIterations}):`;
      agentPrompt += `\nReason: ${task.judgementFeedback.lastJudgement.reason}`;
      if (task.judgementFeedback.lastJudgement.missingRequirements.length > 0) {
        agentPrompt += `\n\nMissing requirements:`;
        for (const req of task.judgementFeedback.lastJudgement.missingRequirements) {
          agentPrompt += `\n  - ${req}`;
        }
      }
      agentPrompt += `\n\nPlease address these issues and complete the task.`;
    }

    const agentResult =
      deps.agentType === 'claude'
        ? await deps.runnerEffects.runClaudeAgent(agentPrompt, worktreePath as string, deps.model!, theRunId)
        : await deps.runnerEffects.runCodexAgent(agentPrompt, worktreePath as string, deps.model, theRunId);

    // 6. 結果をログに記録
    if (isErr(agentResult)) {
      const errorMsg = agentResult.err.message;
      await deps.runnerEffects.appendLog(
        theRunId,
        `[${new Date().toISOString()}] ❌ Agent execution failed\n`,
      );
      await deps.runnerEffects.appendLog(theRunId, `Error: ${errorMsg}\n`);

      // メタデータ更新（失敗）
      const failedRun = {
        ...run,
        status: RunStatus.FAILURE,
        finishedAt: new Date().toISOString(),
        errorMessage: errorMsg,
      };
      await deps.runnerEffects.saveRunMetadata(failedRun);

      return createOk({
        runId: theRunId,
        success: false,
        error: errorMsg,
      });
    }

    // 7. 成功時の処理
    const output = agentResult.val;

    await deps.runnerEffects.appendLog(
      theRunId,
      `[${new Date().toISOString()}] ✅ Agent execution completed\n`,
    );
    await deps.runnerEffects.appendLog(theRunId, `Final Response:\n${output.finalResponse}\n`);

    // メタデータ更新（成功）
    const completedRun = {
      ...run,
      status: RunStatus.SUCCESS,
      finishedAt: new Date().toISOString(),
    };
    await deps.runnerEffects.saveRunMetadata(completedRun);

    return createOk({
      runId: theRunId,
      success: true,
    });
  };

  /**
   * 変更をコミット
   *
   * WHY: config.commit.autoSignatureで自動コミット時の署名を制御。
   *      Worker実行時の各タスクコミットはデフォルトで署名なし（開発効率重視）。
   *
   * @param task タスク
   * @param worktreePath worktreeのパス
   * @returns Result型
   */
  const commitChanges = async (
    task: Task,
    worktreePath: WorktreePath,
  ): Promise<Result<void, OrchestratorError>> => {
    // 変更をステージング
    const stageResult = await deps.gitEffects.stageAll(worktreePath);
    if (isErr(stageResult)) {
      return createErr(stageResult.err);
    }

    // コミットメッセージを生成
    const commitMessage = generateCommitMessage(task);

    // コミットオプション設定（署名制御）
    const noGpgSign = !deps.config.commit.autoSignature;

    // コミット
    const commitResult = await deps.gitEffects.commit(worktreePath, commitMessage, { noGpgSign });
    if (isErr(commitResult)) {
      return createErr(commitResult.err);
    }

    return createOk(undefined);
  };

  /**
   * リモートにpush
   *
   * WHY: worktreeの現在のブランチ名を取得してpushすることで、serial chain実行時の
   *      ブランチ名の不一致を防ぐ（最初のタスクのブランチ名を使用）
   * WHY: リモートが存在しない場合はpushをスキップ（ローカル開発環境への対応）
   *
   * @param worktreePath worktreeのパス
   * @returns Result型
   */
  const pushChanges = async (
    worktreePath: WorktreePath,
  ): Promise<Result<void, OrchestratorError>> => {
    // リモートの存在を確認
    const hasRemoteResult = await deps.gitEffects.hasRemote(worktreePath, 'origin');
    if (isErr(hasRemoteResult)) {
      return createErr(hasRemoteResult.err);
    }

    if (!hasRemoteResult.val) {
      // リモートが存在しない場合は警告を表示してスキップ
      console.warn(`  ⚠️  Remote 'origin' not found, skipping push`);
      return createOk(undefined);
    }

    // worktreeの現在のブランチ名を取得
    const currentBranchResult = await deps.gitEffects.getCurrentBranch(repoPath(worktreePath));
    if (isErr(currentBranchResult)) {
      return createErr(currentBranchResult.err);
    }

    const currentBranch = currentBranchResult.val;
    const pushResult = await deps.gitEffects.push(worktreePath, 'origin', currentBranch);

    if (isErr(pushResult)) {
      return createErr(pushResult.err);
    }

    return createOk(undefined);
  };

  /**
   * Worktreeをクリーンアップ（削除）
   *
   * WHY: 3.3 エッジケース - タスク完了後のworktree削除（通常と統合ブランチ用）
   *
   * @param taskId タスクID
   * @returns Result型
   */
  const cleanupWorktree = async (taskId: TaskId): Promise<Result<void, OrchestratorError>> => {
    // タスク情報を取得して integrationRetried フラグを確認
    const taskResult = await deps.taskStore.readTask(taskId);

    // 通常のworktreeを削除
    const removeResult = await deps.gitEffects.removeWorktree(deps.appRepoPath, taskId);

    // 統合ブランチ用のworktree（存在する場合）も削除
    if (taskResult.ok && taskResult.val.integrationRetried) {
      const integrationWorktreeName = `${String(taskId)}-integration`;
      const removeIntegrationResult = await deps.gitEffects.removeWorktree(
        deps.appRepoPath,
        integrationWorktreeName,
      );

      if (isErr(removeIntegrationResult)) {
        // 統合worktreeの削除失敗は警告のみ（通常worktreeの削除結果を優先）
        console.warn(
          `Failed to remove integration worktree ${integrationWorktreeName}: ${removeIntegrationResult.err.message}`,
        );
      }
    }

    return removeResult;
  };

  /**
   * 既存のworktreeでタスクを実行
   *
   * WHY: 直列チェーンのタスクは同じworktreeを共有することで、前のタスクの変更を引き継げる
   *
   * @param task タスク
   * @param worktreePath 既存のworktreeパス
   * @param previousFeedback 前のタスクのフィードバック（任意）
   * @returns 実行結果
   */
  const executeTaskInExistingWorktree = async (
    task: Task,
    worktreePath: WorktreePath,
    previousFeedback?: string,
  ): Promise<Result<WorkerResult, OrchestratorError>> => {
    // 1. runsディレクトリを確保
    const ensureResult = await deps.runnerEffects.ensureRunsDir();
    if (isErr(ensureResult)) {
      return createErr(ensureResult.err);
    }

    // 2. RunID生成（タスクIDベース）
    const timestamp = Date.now();
    const theRunId = runId(`run-${task.id}-${timestamp}`);
    const logPath = path.join(deps.agentCoordPath, 'runs', `${theRunId}.log`);

    // 3. 実行メタデータを初期化
    const run = createInitialRun({
      id: theRunId,
      taskId: task.id,
      agentType: deps.agentType,
      logPath,
      plannerRunId: task.plannerRunId ?? null,
      plannerLogPath: task.plannerLogPath ?? null,
      plannerMetadataPath: task.plannerMetadataPath ?? null,
    });

    // メタデータ保存
    const saveMetaResult = await deps.runnerEffects.saveRunMetadata(run);
    if (isErr(saveMetaResult)) {
      return createErr(saveMetaResult.err);
    }

    // ログファイルのヘッダーを初期化
    const initLogResult = await deps.runnerEffects.initializeLogFile(run);
    if (isErr(initLogResult)) {
      return createErr(initLogResult.err);
    }

    console.log(`  📝 Execution log: ${getRunDisplayPath(theRunId, 'log')}`);
    console.log(`  📊 Metadata: ${getRunDisplayPath(theRunId, 'json')}`);

    // 4. ログにタスク開始を記録
    await deps.runnerEffects.appendLog(
      theRunId,
      `[${new Date().toISOString()}] Starting task: ${task.acceptance}\n`,
    );
    await deps.runnerEffects.appendLog(theRunId, `Agent Type: ${deps.agentType}\n`);
    await deps.runnerEffects.appendLog(theRunId, `Worktree: ${worktreePath} (reused)\n`);

    if (previousFeedback) {
      await deps.runnerEffects.appendLog(
        theRunId,
        `Previous task feedback:\n${previousFeedback}\n\n`,
      );
    }

    // 5. エージェントを実行（プロンプトにフィードバックを追加）
    // WHY: task.context には詳細な実装指示が含まれるため、必ずプロンプトに含める
    let agentPrompt = `Execute task: ${task.acceptance}

${task.context ? `## IMPLEMENTATION DETAILS\n${task.context}\n` : ''}
${task.scopePaths.length > 0 ? `## FILES TO CREATE/MODIFY\n${task.scopePaths.join('\n')}\n` : ''}

⚠️  CRITICAL: You must IMPLEMENT the task, not just verify it.
- CREATE or MODIFY the files listed above
- If files already exist, verify they meet requirements OR update them
- Ensure your changes are saved and ready to be committed
- The "VERIFY" section describes how to validate completion, not the entire task

⚠️  IMPORTANT: You are working in an isolated worktree directory.
- Your working directory is: ${worktreePath}
- DO NOT use 'cd ..' or navigate outside this directory
- All work must be done within this directory
- The worktree is properly configured with the correct branch

⚠️  IMPORTANT: DO NOT create report files in the repository
- DO NOT create VERIFICATION_REPORT.md or any other report files
- Output verification results directly to logs (stdout/stderr)
- Use console.log, console.error for verification output
- Reports are automatically saved to the runs/ directory by the orchestrator`;

    if (previousFeedback) {
      agentPrompt += `\n\nPrevious task feedback:\n${previousFeedback}`;
    }

    // Judge判定フィードバックがある場合は追加（継続実行のため）
    // WHY: 前回の判定で指摘された問題を明示することで、エージェントが適切に対処できる
    if (task.judgementFeedback) {
      agentPrompt += `\n\n⚠️  Previous attempt (iteration ${task.judgementFeedback.iteration}/${task.judgementFeedback.maxIterations}):`;
      agentPrompt += `\nReason: ${task.judgementFeedback.lastJudgement.reason}`;
      if (task.judgementFeedback.lastJudgement.missingRequirements.length > 0) {
        agentPrompt += `\n\nMissing requirements:`;
        for (const req of task.judgementFeedback.lastJudgement.missingRequirements) {
          agentPrompt += `\n  - ${req}`;
        }
      }
      agentPrompt += `\n\nPlease address these issues and complete the task.`;
    }

    const agentResult =
      deps.agentType === 'claude'
        ? await deps.runnerEffects.runClaudeAgent(agentPrompt, worktreePath as string, deps.model!, theRunId)
        : await deps.runnerEffects.runCodexAgent(agentPrompt, worktreePath as string, deps.model, theRunId);

    // 6. 結果をログに記録
    if (isErr(agentResult)) {
      const errorMsg = agentResult.err.message;
      await deps.runnerEffects.appendLog(
        theRunId,
        `[${new Date().toISOString()}] ❌ Agent execution failed\n`,
      );
      await deps.runnerEffects.appendLog(theRunId, `Error: ${errorMsg}\n`);

      // メタデータ更新（失敗）
      const failedRun = {
        ...run,
        status: RunStatus.FAILURE,
        finishedAt: new Date().toISOString(),
        errorMessage: errorMsg,
      };
      await deps.runnerEffects.saveRunMetadata(failedRun);

      return createOk({
        runId: theRunId,
        success: false,
        error: errorMsg,
      });
    }

    // 7. 成功時の処理
    const output = agentResult.val;

    await deps.runnerEffects.appendLog(
      theRunId,
      `[${new Date().toISOString()}] ✅ Agent execution completed\n`,
    );
    await deps.runnerEffects.appendLog(theRunId, `Final Response:\n${output.finalResponse}\n`);

    // メタデータ更新（成功）
    const completedRun = {
      ...run,
      status: RunStatus.SUCCESS,
      finishedAt: new Date().toISOString(),
    };
    await deps.runnerEffects.saveRunMetadata(completedRun);

    return createOk({
      runId: theRunId,
      success: true,
    });
  };

  /**
   * タスクを実行（全体のオーケストレーション）
   *
   * 1. worktreeを作成（依存関係に応じた処理）
   * 2. コンフリクトがある場合は、その場で解決
   * 3. Workerエージェントを起動
   * 4. 変更をコミット
   * 5. リモートにpush
   *
   * @param task 実行するタスク
   * @param resolution ベースブランチ解決結果（依存関係のパターン）
   * @returns 実行結果
   */
  const executeTaskWithWorktree = async (
    task: Task,
    resolution: BaseBranchResolution,
  ): Promise<Result<WorkerResult, OrchestratorError>> => {
    try {
      // 1. Worktreeを作成（resolutionの型に応じて処理を分岐）
      let setupResult: Result<WorktreeSetupResult, OrchestratorError>;

      switch (resolution.type) {
        case 'none': {
          // 依存なし: HEADから分岐
          const noneResult = await setupWorktree(task);
          setupResult = noneResult.ok
            ? createOk({ type: 'success', worktreePath: noneResult.val })
            : noneResult;
          break;
        }
        case 'single': {
          // 単一依存: 依存先ブランチから分岐
          const singleResult = await setupWorktree(task, resolution.baseBranch);
          setupResult = singleResult.ok
            ? createOk({ type: 'success', worktreePath: singleResult.val })
            : singleResult;
          break;
        }
        case 'multi':
          // 複数依存: worktree内でマージ
          setupResult = await setupWorktreeWithMerge(task, resolution.dependencyBranches);
          break;
      }

      if (isErr(setupResult)) {
        return createErr(setupResult.err);
      }

      const result = setupResult.val;
      let worktreePath: WorktreePath;

      // 2. コンフリクトがある場合は、その場で解決
      // WHY: Worker自身が解決することで、タスク失敗→依存ブロックの連鎖を防ぐ
      if (result.type === 'with_conflicts') {
        worktreePath = result.worktreePath;
        const { conflictInfo } = result;

        console.log(`  ⚠️  Merge conflicts detected in ${conflictInfo.conflicts.length} file(s)`);

        // コンフリクト解決プロンプトを構築
        const conflictPrompt = buildConflictResolutionPromptInline(conflictInfo);

        // Issue 1: コンフリクト解決用のRunIDを生成
        // WHY: コンフリクト解決の実行履歴を追跡可能にする
        const ensureResult = await deps.runnerEffects.ensureRunsDir();
        if (isErr(ensureResult)) {
          await deps.gitEffects.abortMerge(repoPath(worktreePath));
          await cleanupWorktree(task.id);
          return createErr(ensureResult.err);
        }

        const conflictResolutionRunId = runId(`conflict-resolution-${task.id}-${Date.now()}`);
        const conflictRun = createInitialRun({
          id: conflictResolutionRunId,
          taskId: task.id,
          agentType: deps.agentType,
          logPath: path.join(deps.agentCoordPath, 'runs', `${conflictResolutionRunId}.log`),
        });

        const saveMetaResult = await deps.runnerEffects.saveRunMetadata(conflictRun);
        if (isErr(saveMetaResult)) {
          await deps.gitEffects.abortMerge(repoPath(worktreePath));
          await cleanupWorktree(task.id);
          return createErr(saveMetaResult.err);
        }

        const initLogResult = await deps.runnerEffects.initializeLogFile(conflictRun);
        if (isErr(initLogResult)) {
          await deps.gitEffects.abortMerge(repoPath(worktreePath));
          await cleanupWorktree(task.id);
          return createErr(initLogResult.err);
        }

        console.log(
          `  📝 Conflict resolution log: ${getRunDisplayPath(conflictResolutionRunId, 'log')}`,
        );

        // Claudeにコンフリクト解決を依頼
        const resolutionResult =
          deps.agentType === 'claude'
            ? await deps.runnerEffects.runClaudeAgent(
                conflictPrompt,
                worktreePath as string,
                deps.model!,
                conflictResolutionRunId,
              )
            : await deps.runnerEffects.runCodexAgent(
                conflictPrompt,
                worktreePath as string,
                deps.model,
                conflictResolutionRunId,
              );

        if (isErr(resolutionResult)) {
          // コンフリクト解決失敗
          console.log(
            `  ❌ Failed to resolve merge conflicts: ${resolutionResult.err.message}`,
          );

          // メタデータ更新（失敗）
          const failedRun = {
            ...conflictRun,
            status: RunStatus.FAILURE,
            finishedAt: new Date().toISOString(),
            errorMessage: resolutionResult.err.message,
          };
          await deps.runnerEffects.saveRunMetadata(failedRun);

          await deps.gitEffects.abortMerge(repoPath(worktreePath));
          await cleanupWorktree(task.id);
          return createErr(resolutionResult.err);
        }

        // メタデータ更新（成功）
        const completedRun = {
          ...conflictRun,
          status: RunStatus.SUCCESS,
          finishedAt: new Date().toISOString(),
        };
        await deps.runnerEffects.saveRunMetadata(completedRun);

        // コンフリクト解決成功: 変更をステージングしてコミット
        const stageResult = await deps.gitEffects.stageAll(worktreePath);
        if (isErr(stageResult)) {
          await deps.gitEffects.abortMerge(repoPath(worktreePath));
          await cleanupWorktree(task.id);
          return createErr(stageResult.err);
        }

        // Issue 5: コンフリクトマーカーが残っていないかチェック
        // WHY: LLMが解決に失敗し、コンフリクトマーカーが残ったままコミットされるのを防ぐ
        const diffResult = await deps.gitEffects.getDiff(worktreePath, ['--cached']);
        if (isErr(diffResult)) {
          console.log(`  ⚠️  Failed to check for conflict markers: ${diffResult.err.message}`);
          // diff取得失敗は致命的ではないため、警告のみ
        } else {
          const diff = diffResult.val;
          const hasConflictMarkers =
            diff.includes('<<<<<<<') || diff.includes('=======') || diff.includes('>>>>>>>');

          if (hasConflictMarkers) {
            console.log(`  ❌ Conflict markers still present after resolution`);
            await deps.gitEffects.abortMerge(repoPath(worktreePath));
            await cleanupWorktree(task.id);
            return createErr({
              type: 'ValidationError',
              message: 'Conflict resolution incomplete: conflict markers still present',
              details:
                'The agent failed to fully resolve conflicts. Manual intervention is required.',
            });
          }
        }

        const commitResult = await deps.gitEffects.commit(
          worktreePath,
          'Resolve merge conflicts from dependencies',
          { noGpgSign: !deps.config.commit.autoSignature },
        );

        if (isErr(commitResult)) {
          // Issue 2: コミット失敗時にマージを中断
          console.log(`  ❌ Failed to commit conflict resolution: ${commitResult.err.message}`);
          await deps.gitEffects.abortMerge(repoPath(worktreePath));
          await cleanupWorktree(task.id);
          return createErr(commitResult.err);
        }

        console.log(`  ✅ Merge conflicts resolved`);

        // Phase 4: コンフリクト解決後に依存関係の再インストール（必要な場合）
        if (conflictInfo.needsReinstall) {
          console.log(`  📦 Reinstalling dependencies...`);
          const installResult = await runCommand(worktreePath, 'pnpm', ['install']);
          if (!installResult.ok) {
            console.log(`  ⚠️  Failed to reinstall dependencies: ${installResult.err.message}`);
            // 再インストール失敗は警告のみ、タスク実行は継続
          } else {
            console.log(`  ✅ Dependencies reinstalled`);
          }
        }
      } else {
        worktreePath = result.worktreePath;
      }

      // 3. タスクを実行
      const runResult = await executeTask(task, worktreePath);
      if (isErr(runResult)) {
        return createErr(runResult.err);
      }

      const workerResult = runResult.val;

      if (!workerResult.success) {
        // エージェント実行失敗時はWorkerResultをそのまま返す
        return createOk(workerResult);
      }

      // 4. 変更をコミット
      const commitResult = await commitChanges(task, worktreePath);
      if (isErr(commitResult)) {
        return createErr(commitResult.err);
      }

      // 5. リモートにpush
      const pushResult = await pushChanges(worktreePath);
      if (isErr(pushResult)) {
        return createErr(pushResult.err);
      }

      return createOk(workerResult);
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      return createOk({
        runId: `error-${task.id}`,
        success: false,
        error: errorMessage,
      });
    }
  };

  /**
   * 既存worktreeの状態を維持してタスクを続行
   *
   * WHY: 失敗したタスクを「続きから引き継ぐ」際、既存のworktreeとログを利用して続行する
   *
   * @param task 実行するタスク
   * @returns 実行結果
   */
  const continueTask = async (task: Task): Promise<Result<WorkerResult, OrchestratorError>> => {
    try {
      // 1. 既存worktreeの存在を確認（listWorktreesを使用）
      const worktreesResult = await deps.gitEffects.listWorktrees(deps.appRepoPath);
      if (isErr(worktreesResult)) {
        console.log(`  ⚠️  Failed to list worktrees, falling back to normal execution`);
        // 継続実行に失敗した場合は、依存関係なしとして通常実行
        return await executeTaskWithWorktree(task, { type: 'none' });
      }

      const worktrees = worktreesResult.val;
      const taskWorktree = worktrees.find((wt) => {
        // Worktreeのパスに task.id が含まれているかチェック
        return String(wt.path).includes(String(task.id));
      });

      if (!taskWorktree) {
        console.log(
          `  ⚠️  Worktree for task ${task.id} not found, falling back to normal execution`,
        );
        // 継続実行に失敗した場合は、依存関係なしとして通常実行
        return await executeTaskWithWorktree(task, { type: 'none' });
      }

      const existingWorktreePath = taskWorktree.path;

      // 2. 前回の実行ログを読み込む（存在する場合）
      let previousLog: string | undefined;
      const logFilesResult = await deps.runnerEffects.listRunLogs();
      const logFiles = logFilesResult.ok ? logFilesResult.val : [];

      // タスクIDに関連するログファイルを検索
      const taskLogs = logFiles.filter((logFile) => logFile.includes(String(task.id)));

      if (taskLogs.length > 0) {
        // 最新のログを取得（ファイル名から.logを除去してrunIdとして使用）
        const latestLogFile = taskLogs[taskLogs.length - 1];
        const runIdStr = latestLogFile?.replace('.log', '') ?? '';

        const logContentResult = await deps.runnerEffects.readLog(runIdStr);
        if (logContentResult.ok) {
          previousLog = logContentResult.val;
          console.log(`  📋 Loaded previous execution log: ${latestLogFile}`);
        }
      }

      // 3. エージェントを実行（previousLogをフィードバックとして渡す）
      const runResult = await executeTaskInExistingWorktree(
        task,
        existingWorktreePath,
        previousLog,
      );

      if (isErr(runResult)) {
        return createErr(runResult.err);
      }

      const result = runResult.val;

      if (!result.success) {
        return createOk(result);
      }

      // 4. 変更をコミット
      const commitResult = await commitChanges(task, existingWorktreePath);
      if (isErr(commitResult)) {
        return createErr(commitResult.err);
      }

      // 5. リモートにpush
      const pushResult = await pushChanges(existingWorktreePath);
      if (isErr(pushResult)) {
        return createErr(pushResult.err);
      }

      return createOk(result);
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      return createOk({
        runId: `error-${task.id}`,
        success: false,
        error: errorMessage,
      });
    }
  };

  return {
    setupWorktree,
    executeTask,
    executeTaskInExistingWorktree,
    commitChanges,
    pushChanges,
    cleanupWorktree,
    executeTaskWithWorktree,
    continueTask,
  };
};
